practice-app/server/src/api/validators/category.validator.js
practice-app/server/src/models/category.js
practice-app/server/src/models/index.js

As progress continued in #163, following actions are taken:
- Determine fields of the category schema
- Determine field properties
- Create the schema
- Create validator.
And now, a review is requested for merge.

Initializing category model

---

practice-app/server/package-lock.json
practice-app/server/package.json
practice-app/server/src/api/controllers/category/createCategory.js
practice-app/server/src/api/controllers/category/createCategoryEndpoint.js
practice-app/server/src/api/controllers/category/index.js
practice-app/server/src/api/routes/category.js
practice-app/server/src/api/routes/index.js
practice-app/server/src/api/validators/category.validator.js
practice-app/server/src/config/index.js
practice-app/server/src/loaders/mongoose.js
practice-app/server/src/models/category.js
practice-app/server/src/models/index.js

As discussed under #165, I implemented post endpoint for api/category.
This endpoint concerns creating new categories in the api. Documentation for it can be found [here](https://documenter.getpostman.com/view/18740569/UyxdL99r)

Implementation of POST /api/category endpoint

---

practice-app/server/package-lock.json
practice-app/server/package.json
practice-app/server/src/api/controllers/category/createCategory.js
practice-app/server/src/api/controllers/category/createCategoryEndpoint.js
practice-app/server/src/api/controllers/category/getCategoryEndpoint.js
practice-app/server/src/api/controllers/category/index.js
practice-app/server/src/api/routes/category.js
practice-app/server/src/api/routes/index.js
practice-app/server/src/api/validators/category.validator.js
practice-app/server/src/config/index.js
practice-app/server/src/loaders/mongoose.js
practice-app/server/src/models/category.js
practice-app/server/src/models/index.js

As described in #167, get endpoint for /api/category endpoint is implemented and tested using Postman.
Its documentation can be achieved [here](https://documenter.getpostman.com/view/18740569/UyxdL99r).
I believe it is fully functional and ready to be merged.

Implementation of GET /api/category endpoint -167

---

practice-app/server/package-lock.json
practice-app/server/package.json
practice-app/server/test/post.category.test.js

As mentioned in #170, I implemented unit tests for POST /api/category endpoint.
These unit tests check for following cases:
- If a category is successfully created
- What if a category already exists
- What if title is too short
- What if title does not exists

Implementing Unit tests for post /api/category -170

---

package-lock.json
practice-app/package-lock.json
practice-app/server/package-lock.json
practice-app/server/package.json
practice-app/server/src/api/controllers/user/dropLesson.js
practice-app/server/src/api/controllers/user/index.js
practice-app/server/src/api/routes/user.js
practice-app/server/src/api/validators/user.validator.js
practice-app/server/src/models/user.js

1. Check whether the incoming data is valid or not
2. Check whether a user with the given user_id and a lesson with the given lesson_id exists or not.
3. Check whether the user with the given user_id takes the lesson with the given lesson_id or not.
4. Remove the lesson from user's enrollment list and return the user and lesson with a success message
5. Return an error message if an error occurs in any of the previous steps
6. Test the endpoint with Postman
7. Save requests as a collection in Postman
8. Document the endpoint
Now, the drop lesson endpoint is ready for requests.
This PR closes #174 , other details can also be seen from that issue.

Implement the drop lesson endpoint

---

practice-app/server/src/api/controllers/user/dropLesson.js

In this pull request I just changed 3 error status codes from 400 to 404.

Changed some error codes

---

practice-app/server/test/drop_lesson.test.js

1. Determine the steps to test
2. Create the base test files
3. Write unit tests for the determined steps:
* Created dummy object IDs
* Created 1 dummy category
* Created 3 dummy lessons under that category
* Created 2 dummy users takes those lessons
* Added dummy category, lessons and users
* Tested the actions determined above
* Deleted dummy created data
Now, the tests for the drop lesson endpoint are ready and tested. The drop lesson endpoint passed all tests successfully without any problem.
This PR closes #199, other details can also be seen from that issue.

Test for drop lesson endpoint is implemented

---

practice-app/server/src/api/controllers/user/attendEvent.js
practice-app/server/src/api/controllers/user/index.js
practice-app/server/src/api/routes/user.js
practice-app/server/src/api/validators/user.validator.js
practice-app/server/src/models/user.js

1. Check whether the incoming data is valid
2. Check whether the user and event exists
3. Check whether or not the user has already attended the event
4. Add the event to the user's attended events list and return the user and event with a success message
5. Return an error message if an error occurs in any of the previous steps
6. Test the endpoint with Postman
7. Save requests as a collection in Postman
8. Document the endpoint
Now, the attend event endpoint is ready for requests.
This PR closes #192 , other details can also be seen from that issue.

Implementing the Attend Event Endpoint

---

practice-app/server/src/api/controllers/user/getAttendedEvents.js
practice-app/server/src/api/controllers/user/index.js
practice-app/server/src/api/routes/user.js
practice-app/server/test/get.attended_events.test.js

As mentioned in the #218, I will be implementing the unit tests for GET attended events endpoint. As described in the issue, there will be 2 scenarios that the endpoint will be tested:
1. Successful fetch of attended events of the user
2. Request with an invalid user_id

Implementing unit tests for GET api/user/attendedEvents endpoint

---

practice-app/server/src/api/controllers/user/getAttendedEvents.js
practice-app/server/src/api/controllers/user/index.js
practice-app/server/src/api/routes/user.js

This pull request is about fetching attended events of a user operation, concerning a GET endpoint of our API called /user/attendedEvents. As discussed in #217 I will be implementing this GET endpoint and test my implementation using Postman.
After the implementation and testing stages are done, I will be preparing a documentation for the API regarding this GET endpoint.

Implementation of GET /api/user/attendedEvents endpoint

---

practice-app/server/test/attend_event.test.js

1. Determine the steps to test
2. Create the base test files
3. Write unit tests for the determined steps:
* Created dummy object IDs
* Created 3 dummy events
* Created 2 dummy users who will attend above events
* Added dummy events and users
* Tested the actions determined above
* Deleted dummy created data
Now, the tests for the attend event endpoint are ready and tested. The attend event endpoint passed all tests successfully without any problem.
This PR closes #226 , other details can also be seen from that issue.

Writing the Unit Tests for the Attend Event Endpoint

---

practice-app/server/package-lock.json
practice-app/server/src/api/controllers/lesson/get_lesson_events.js
practice-app/server/test/get_lesson_events.test.js

1. Determine the steps to test
2. Create the base test files
3. Write unit tests for the determined steps:
* Created dummy object IDs
* Created 1 dummy category
* Created 2 dummy lessons under that category
* Created 2 dummy users 
* Created 3 dummy events
* Added dummy category, lessons, users and events
* Tested the actions determined above
* Deleted dummy created data
Now, the tests for the get lesson events endpoint are ready and tested. The get lesson events endpoint passed all tests successfully without any problem.
This PR closes #224, other details can also be seen from that issue.

Practice app/feature/get lesson events tests 224

---

practice-app/server/src/api/routes/index.js

I fixed the minor bug. Event was exported and used twice in the server/src/api/routes/index.js . I deleted one of them. You can view from the changed files.

Practice App: FIX | Deleted additional import and use of event.

---

practice-app/server/test/enroll_lesson.test.js

As mentioned in the [issue 250](https://github.com/bounswe/bounswe2022group2/issues/250) I will be implementing the unit tests for POST endpoint of enrolling lessons.
1. Successful enrolling to a lesson
2. Request with missing user_id
3. Request with missing lesson_id
4. Request with invalid user_id
5. Request with invalid lesson_id
6. Request with user_id which does not exist
7. Request with lesson_id which does not exist
8. Request with user_id which is already taken this course

Create enroll lesson unit test

---

practice-app/server/src/api/controllers/category/filterByName.js
practice-app/server/src/api/controllers/category/index.js
practice-app/server/src/api/routes/category.js

This PR includes following actions:
Search the data in categories
Return an error message if an error occurs
Test the endpoint with Postman
Save requests as a collection in Postman
Document the endpoint

Implementation of Searching Categories by Name

---

practice-app/server/src/api/controllers/user/login.js
practice-app/server/test/enroll_lesson.test.js
practice-app/server/test/login.test.js

I have implemented test for post login endpoint. Also fixed minor bugs. It is ready to be reviewed. If there is no need to change anything, you can directly merge. Also, this PR closes #213.

Practice App: Test | Implemented POST Login Endpoint Test

---

practice-app/server/test/post.event.test.js

Although the implementation of the unit tests for creating events POST endpoint is done and merged to the master in #245, since there is an update in the lesson model by other team members, I am updating my unit test accordingly.
Now, they should be all up and running.

BUGFIX: Create Event Unit Tests - Lesson Model Update

---

practice-app/frontend/package-lock.json
practice-app/frontend/package.json
practice-app/frontend/src/components/Login.vue
practice-app/server/package-lock.json
practice-app/server/package.json
practice-app/server/src/api/controllers/user/login.js
practice-app/server/test/enroll_lesson.test.js

I have implemented login screen. All of the functionalities were tested. If you have any further suggestions and questions, I'm  ready to answer. If you think there is no need to change anything, you can directly merge. This PR closes #262.

Practice app: Frontend | Implemented Login Screen

---

practice-app/frontend/src/App.vue
practice-app/frontend/src/components/EnrolledLessons.vue
practice-app/frontend/src/route.js

As mentioned in the issue #251, I took the responsibility of implementation of the enrolled lessons page of our practice app. Before starting to develop the enrolled lessons page, I created the corresponding endpoints and their unit tests. After being sure that the endpoints work successfully and after testing it with both unit tests and via postman manually, I started to develop the enrolled lessons page with the Vue.js framework according to the team's decision.
* Sending GET and POST requests to our backend server via correct parameters
* Implementation of enrolled lessons page and drop lesson functionality inside it
This PR closes #251, other details can also be seen from that issue.

Added enrolled lessons page and drop lesson functionality

---

practice-app/server/test/enroll_lesson.test.js
practice-app/server/test/get_lessons_by_name.test.js

I have implemented test for the get lecture by name endpoint. Everything works fine. If you think there is no need to change anything, you can directly merge. This PR closes #214.

Practice App: Test | Implemented GET Lecture by Name Endpoint Test

---

practice-app/frontend/src/App.vue
practice-app/frontend/src/components/Attend.vue
practice-app/frontend/src/route.js

As mentioned in the issue #286 , I took the responsibility of implementation of the attend event page of our practice app. Before starting to develop the attend event page, I created the corresponding endpoints and their unit tests. After being sure that the endpoints work successfully and after testing it with both unit tests and via postman manually, I started to develop the attend event page with the Vue.js framework according to the team's decision.
* Sending POST requests to our backend server via correct parameters
* Implementation of the attend event page functionality.
This PR closes #286 , other details can also be seen from that issue.

Practice App: Create Attend Event Screen

---

practice-app/frontend/src/App.vue
practice-app/frontend/src/components/EnrolledLessons.vue
practice-app/frontend/src/components/LessonEvents.vue
practice-app/frontend/src/route.js

As mentioned in the issue #289 , I took the responsibility of implementation of the lesson events page of our practice app. Before starting to develop the lesson events page, I created the corresponding endpoints and their unit tests. After being sure that the endpoints work successfully and after testing it with both unit tests and via postman manually, I started to develop the lesson events page with the Vue.js framework according to the team's decision.
* Sending GET request to our backend server via correct parameter
* Implementation of lesson events page and get lesson events functionality inside it
This PR closes #289 , other details can also be seen from that issue.

Practice app/feature/frontend get lesson events 289

---

practice-app/frontend/src/App.vue
practice-app/frontend/src/components/SearchLesson.vue
practice-app/frontend/src/route.js

I have implemented search lecture page. All of the functionalities were tested. If you have any further suggestions and questions, I'm ready to answer. If you think there is no need to change anything, you can directly merge. This PR closes #263.

Practice App: Frontend | Implemented Search Lecture by Name Page

---

practice-app/frontend/src/components/Event.vue

We already been here many times, we need to change localhost to env variable so that in production we can change the backend address.

Changing static localhost URI to environment variable

---

practice-app/frontend/src/route.js

With this, we can reload our pages.

not reloading problem

---

learnify/mobile/lib/core/base/view-model/base_view_model.dart
learnify/mobile/lib/core/managers/navigation/l_navigation_manager.dart
learnify/mobile/lib/core/managers/navigation/navigation_manager.dart
learnify/mobile/lib/core/managers/navigation/navigation_route.dart
learnify/mobile/lib/core/providers/provider_list.dart
learnify/mobile/lib/main.dart
learnify/mobile/lib/product/constants/navigation_constants.dart

This PR creates the navigation manager structure in the app to manage the navigation-related stuff in the app in a more structured way. The following implementations are performed with this pull request:
1. Create an abstract navigation manager
2. Create the navigation manager by implementing the abstract one
3. Implement navigateToPage method
4. Implement navigateToPageClear method
5. Integrate the navigation manager into the material app
6. Implement the navigation route
Closes #356

Implementation of the Navigation Manager

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/core/constants/enums/app_themes.dart
learnify/mobile/lib/core/extensions/string/string_extensions.dart
learnify/mobile/lib/core/providers/language/app_localizations.dart
learnify/mobile/lib/core/providers/language/language_provider.dart
learnify/mobile/lib/core/providers/theme/theme_provider.dart
learnify/mobile/lib/product/language/language_keys.dart
learnify/mobile/lib/product/language/language_options.dart
learnify/mobile/lib/product/theme/dark_theme.dart
learnify/mobile/lib/product/theme/light_theme.dart
learnify/mobile/lib/product/theme/theme_types.dart
learnify/mobile/pubspec.yaml

This PR creates the base structure for multi-language and multi-theme supports in the app. We will be able to use theme components and we will be able to translate app texts easily with the help of the changes made in this branch. The following implementations are performed with this pull request:
1.  Implemented theme types enum for light and dark options.
2. Implemented get the current theme and get stored theme methods.
3. Implemented switch theme helper method.
4. Implemented light and dark theme classes using the colors we determined for our app.
5. Implemented app localization class.
6. Implemented language options enum with en and tr options.
7. Implemented get, set, and switch language methods.
8. Implemented load method for language JSON files.
9. Implemented a translate …

Base Setup for Multi Language and Multi Theme Support

---

web/my-app/package-lock.json
web/my-app/package.json
web/my-app/public/index.html
web/my-app/src/App.js
web/my-app/src/pages/Header.js
web/my-app/src/pages/SignInForm.js
web/my-app/src/pages/SignUpForm.js
web/my-app/src/pages/style.css

initial pages are created to offer an example for further design and development

initial pages created to present as an example

---

learnify/web/src/App.js
learnify/web/src/pages/EmailVerificationPage.js
learnify/web/src/pages/HomePage.js
learnify/web/src/pages/SignUpForm.js
learnify/web/src/pages/style.css

We will put into practice the signup, login, forgot password, and email verification pages this week as decided in our third weekly meeting. The frontend team's tasks were likewise divided up. Implementing the email verification screen is my task, and I will develop it completely.
The implementation of the email verification screen and all of its components are included in this Pull Request. The email verification page is implemented and altered to match the design of our online application. No connection to the backend is yet made.

Frontend: Email Verification Page Implementation

---

learnify/backend/.dockerignore
learnify/backend/README.md
learnify/backend/api/controllers/auth/signup.js
learnify/backend/config/index.js
learnify/backend/dockerfile
learnify/backend/package-lock.json
learnify/backend/package.json
learnify/backend/test/post_auth_signup.test.js
learnify/backend/utils/auth/send_verification_email.js

As a huge blunder, we forgot to send verification email in previous signup endpoint implementation.
This PR adds this functionality.

365 sign up endpoint

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md

As it is stated in the Customer Milestone 1 Deliverables instructions, I will create another folder named "CMPE451_Customer_Presentation_Milestone_1" under the "deliverables" folder. I will add the hyperlinks of the mentioned documents in the deliverables MD file. This PR only includes the main deliverables and additionally the individual report of me.
Closes #409

Milestone1: Preparing Deliverables

---

learnify/backend/test/post_auth_verify_email.test.js

This PR is related to #418 and closes it. Unit tests for verify email endpoint is initialized.
In this PR:
1- Unvalid request body is checked
2 - Non-matching verification code checked
3 - Non-existent email checked
4 - Valid request checked.

Backend: Implementing Tests for Verify Email Endpoint

---

learnify/backend/api/controllers/auth/signup.js
learnify/backend/package.json
learnify/backend/utils/auth/send_verification_email.js

Now the backend sends 4 digit code and with a message body.
Topic of the email message is changed.

Sendmail edit

---

learnify/web/package-lock.json
learnify/web/package.json
learnify/web/src/pages/SignUpForm.js
learnify/web/src/pages/style.css

The previous version of the sign up form did not have validation feature, namely any input is considered valid. However, we needed to formalize the inputs to prevent erroneous scenarios. Thus, I have implemented a validation feature to the sign up form.
Although it seems almost identical in the browser, the code and structure is changed a lot, to provide the most optimal validation feature.
For validation and error handling I have used react-hook-form and Yup, while for the error messages I have used bootstrap as I have mentioned in #424

Frontend: Sign Up Form Validation

---

learnify/backend/models/user.js

Our user model returns unnecessary variables(might resulting in security problems) like verification_code and does not return necessary variables like username. 
This PR fixes that.

hotfix: usermodel update

---

learnify/web/src/pages/LoginForm.js
learnify/web/src/pages/style.css

Backend connection has been established for the login page, connected with "/auth/login" endpoint of our API to check whether the user has valid user credentials, in case of successful login user is directed to home-page.

Backend connection for Login Page and Form fields format validation 

---

learnify/web/src/pages/ForgetPassword.js
learnify/web/src/pages/style.css

Backend connection has been established for the forget password page, connected with "/auth/resend" endpoint of our API to send the verification code to email and redirect to the verification page. 
Also, disabling the "Send Code" button if there is not a well formatted e-mail placed in the input field.

backend connection to forget password

---

learnify/mobile/lib/core/base/model/base_model.dart
learnify/mobile/lib/core/managers/local/l_local_manager.dart
learnify/mobile/lib/core/managers/local/local_manager.dart
learnify/mobile/lib/core/managers/navigation/navigation_route.dart
learnify/mobile/lib/core/managers/network/custom_interceptors.dart
learnify/mobile/lib/core/providers/provider_list.dart
learnify/mobile/lib/features/auth/forget-password/view-model/forget_password_view_model.dart
learnify/mobile/lib/features/auth/service/auth_service.dart
learnify/mobile/lib/features/auth/service/l_auth_service.dart
learnify/mobile/lib/features/auth/signup/view-model/signup_view_model.dart
learnify/mobile/lib/features/auth/verification/model/user_model.dart
learnify/mobile/lib/features/auth/verification/model/verify_email_request_model.dart
learnify/mobile/lib/features/auth/verification/model/verify_email_response_model.dart
learnify/mobile/lib/features/auth/verification/view-model/verification_view_model.dart
learnify/mobile/lib/features/auth/verification/view/verification_screen.dart
learnify/mobile/lib/features/home-wrapper/view-model/home_wrapper_view_model.dart
learnify/mobile/lib/features/home-wrapper/view/home_wrapper_screen.dart
learnify/mobile/lib/features/profile/view-model/profile_view_model.dart
learnify/mobile/lib/features/profile/view/profile_screen.dart
learnify/mobile/lib/main.dart
learnify/mobile/lib/product/constants/storage_keys.dart
learnify/mobile/test/profile_screen_test.dart

I implemented:
* Verify email request model
* Verify email response model
* User response model
* POST method to send the entered verification code
* Verify function in verification view model to call POST method
* Resend function in verification view model to call POST method implemented by @ezgy 
Merging this pull request closes #434.

Mobile: Back-End Connection of Verification Screen/434

---

learnify/backend/api/controllers/courses/get_courses.js
learnify/backend/api/controllers/courses/index.js
learnify/backend/api/routes/courses.js
learnify/backend/api/routes/index.js
learnify/backend/migrations/add_mock_courses.js
learnify/backend/models/course.js
learnify/backend/models/index.js

Endpoint implementation of GET /courses
returns mock course data for the milestone 1 presentations
Also comes with a migration to add mock course data to the database.

return mock course data

---

learnify/mobile/test/verification_screen_test.dart

I added network connection tests to verification. It passed all tests, here is the screenshot:
Merging this PR into dev branch closes #454.

Mobile: Verification screen network tests 

---

learnify/mobile/lib/features/home/components/course_preview.dart
learnify/mobile/lib/features/home/view/home_screen.dart

As discussed in #408, a widget was required for the home screen of the mobile app. This pull request includes:
- Custom widget for the course preview
-  Widget with dummy values for ease of view until relevant backend endpoint & request model is implemented. 
Closes #408

Mobile: course preview widget

---

learnify/backend/package-lock.json
learnify/backend/package.json
learnify/backend/test/post_auth_login.test.js

This PR is related to #421 and closes it. Unit tests for login endpoint has been implemented.
1- Unvalid request body check
2- Wrong password check
3- Non-existent email check
4- Login for valid user.

Backend: Implementing Unit Tests for Login endpoint

---

learnify/web/package-lock.json
learnify/web/package.json
learnify/web/src/App.js
learnify/web/src/App.test.js
learnify/web/src/__tests__/SignUpForm.test.js
learnify/web/src/pages/SignUpForm.js

The sign up page was fully implemented and functioning. However, before publishing it into our live website, we need to provide unit tests and the components that are tested should pass the unit tests successfully.
This PR provides unit testing implementation for the sign up page. For the tests I have created a folder under web/src, which named __tests__ . Sign up page is tested by 8 test cases and it has passed from all successfully.
***
* There was an unnecessary App.test.js file. I have deleted it.
***

Frontend: Unit tests for sign up page

---

learnify/web/src/__tests__/EmailVerificationPage.test.js
learnify/web/src/pages/EmailVerificationPage.js

The email verification page was completely operational and deployed. However, we must offer unit tests and the tested components must successfully pass the unit tests before we can publish it to our live website.
The implementation of unit testing for the email verification page is provided by this PR. I have added the unit tests in EmailVerificationPage.test.js file to the subdirectory called __tests__ beneath web/src. The email verification page has successfully passed each of the three test scenarios that it was put through.
***
* I have run the tests and they all worked as expected.
***

Frontend: Unit Tests for Email Verification Page

---

learnify/web/src/__tests__/LoginForm.test.js
learnify/web/src/pages/LoginForm.js

Among the unit test cases the one which is testing the case that the provided e-mail in the form is correct and registered but the password is wrong is using a temporary registered e-mail for now.

Test cases for Login Page has been implemented and tested.

---

learnify/mobile/lib/core/managers/navigation/navigation_route.dart
learnify/mobile/lib/features/auth/service/l_auth_service.dart
learnify/mobile/lib/features/home-wrapper/view/home_wrapper_screen.dart
learnify/mobile/lib/features/home/model/course_model.dart
learnify/mobile/lib/features/home/model/get_courses_response_model.dart
learnify/mobile/lib/features/home/service/I_home_service.dart
learnify/mobile/lib/features/home/service/home_service.dart
learnify/mobile/lib/features/home/view-model/home_view_model.dart
learnify/mobile/lib/features/home/view/home_screen.dart

I need to implement a scrollable horizontal course list widget for the home page of our mobile application. This pull request is related to this task and merging this pull request closes #457 .

Mobile: Scrollable horizontal course list widget for home screen / 457

---

learnify/mobile/README.md

- Adds links to the system manual and APK file wiki pages

Update README.md of the mobile project

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/deliverables.md

adds mobile deliverables namely APK link and system manual to the report.

add mobile deliverables

---

learnify/README.md

I created a readme with setup instructions for our first tage, merge ASAP

create readme.md for learnify folder with setup instructions

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This PR is created for filling the mobile-related sections in the evaluation of tools and processes part. Since it's the first PR related to the group review document, it should also create the base file and structure for milestone 1 - group review document.
------
1. Creates the "group_review.md" file under "deliverables" folder.
2. Creates the base structure for the file with the corresponding titles mentioned in the description folder
3. Fills the mobile-related parts in the evaluation of tools and processes section
4. Fills the individual work and responsibilities sections of "Bahrican Yeşil" (for me)
------
Closes #475

Milestone 1: Evaluation of Tools And Processes - Mobile

---

learnify/mobile/test/login_test.dart

I have implemented the login page with backend connection which can be seen from issue #396 . I completed the tests of login page in this issue as well. 
------
1. Widget test for login page
2. Network test for login page
------
Closes #447

Mobile: Tests for Login Page

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

includes List and Status of deliverables, requirements and individual efforts for the milestone group report
------
1. List and Status of deliverables
2.  requirements 
3.  individual efforts - Ezgi Aysel Batı
------
Closes #473 , #474

add parts and individual efforts

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This PR is opened to merge my personal efforts to our group report for Milestone-1.
------
1. Personal efforts of Egemen Atik for Milestone-1 group report.
------

Add personal efforts of Egemen Atik

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I investigated technologies mentioned above in our tools evaluation section.

adding  AWS, Docker, Gmail and NodeJS to tools evaluation

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This PR includes executive summary for milestone-1.
------
Closes #(498)

Milestone-1: Executive Summary

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I have added my work in the personal efforts sections. After the review, it can be directly merged.

Milestone 1: Adding Personal Efforts of Onur Kömürcü

---

learnify/mobile/lib/features/home-wrapper/view/home_wrapper_screen.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_item.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_list.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart
learnify/mobile/test/chapter_test.dart

I completed the implementation of the chapter section with PR #501. This PR is for writing and merging the tests of the implemented chapter section.
------
1. Tests of the chapter section (in general)
2. Finds each rendered widget in the learning space detail screen including the chapter list, chapter item, and so on
3. Tests the number of elements in the chapter list
4. Tests the activeness and text of the create chapter button
5. Tests the information of the first chapter item (id, title, and so on)
6. Tests the activeness and text of the edit chapter button
------
Closes #478

Completes tests of the chapter section

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I have added my individual contribution to the Milestone 1

Milestone 1: Adding individual work & responsibilities of Altay Acar

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I have created the **Review the Milestone** section of our group review and every sub-section of it, so that @surmelienes1 and @egemenatikk can also add their completed parts. I have also updated the table of contents according to the newly added section.

Milestone 1: Review the Milestone

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This PR includes my individual contribution to Milestone-1 Report.

Milestone-1: Indiviual Contribution

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I present the personal part of group review
------
Personal parts of group review.

responsibility and summary of work for Gokay

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I added my personal contribution to the summary of individual work.

summary of individual work for Batuhan Celik

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

individual changes and evaluation of deliverables
------
individual changes and evaluation of deliverables
------

update indv part and evaluate deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I have added the evaluation of the status of deliverables. Topics were the followings:
1. Software Requirements Specification
2. Software Design (UML)
3. Scenarios and Mockups
4.  Project Plan
Further details can be found under the issue #491.

Evaluation of the Status of Deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This PR was made in order to add the what went well and what did not go well parts to the group review section of our milestone 1 report, alongside my individual contributions in the related section.
------
1. What Went Well and What Could We Have Done Better sections of the group review part of the Milestone-1 report.
2. My individual contributions to the project, Learnify, shown with the issue and pull request links.

Milestone 1: What Went Well, What Did Not Go Well, and Individual Contribution Parts

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

------
1. Summary of individual work for Hasan Can Erol
------

summary of individual work for hasan can erol

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

This is the pr for merging moving forward part of the deliverables.

Adding Moving Forward

---

deliverables/CMPE451_Customer_Presentation_Milestone_1/group_review.md

I have created the evaluation of processes part, and added a team meetings section; for the evaluation of the tools React related part has been added.
Closes #496

Evaluation of Tools, Processes and individual work

---

learnify/web/src/App.js
learnify/web/src/pages/EmailVerificationPage.js
learnify/web/src/pages/ForgetPassword.js
learnify/web/src/pages/LoginForm.js
learnify/web/src/pages/PrivateRoutes.js
learnify/web/src/pages/PrivateRoutesVerify.js
learnify/web/src/pages/SignUpForm.js

I have implemented a rather basic security system namely as private route for our web application as the following stage of our web application development, as we mentioned in [our second frontend team meeting](https://github.com/bounswe/bounswe2022group2/wiki/Meeting-%232-of-the-Frontend-Team). In the later stages of our application development, this security system will be improved.
Private Routes, also known as Protected Routes, demand that a user has permission to access the route (read: page). Therefore, a user cannot visit a page if they are not permitted to do so. The most prevalent illustration is authentication in a React application, where a user may only access the protected pages if they are permitted (which means in this case being authenticated or logged in).
I have used …

Frontend: Implementation of Private Routes

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/core/constants/main_type_definitions.dart
learnify/mobile/lib/core/widgets/buttons/action_button.dart
learnify/mobile/lib/core/widgets/buttons/base_icon_button.dart
learnify/mobile/lib/core/widgets/dialog/dialog_builder.dart
learnify/mobile/lib/core/widgets/divider/custom_vertical_divider.dart
learnify/mobile/lib/core/widgets/text-field/custom_text_form_field.dart
learnify/mobile/lib/core/widgets/text/annotatable/annotatable_text.dart
learnify/mobile/lib/core/widgets/text/annotatable/custom_annotatable_item.dart
learnify/mobile/lib/core/widgets/text/annotatable/custom_text_selection_controls.dart
learnify/mobile/lib/features/auth/login/view-model/login_view_model.dart
learnify/mobile/lib/features/home-wrapper/view/home_wrapper_screen.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_item.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart
learnify/mobile/lib/product/language/language_keys.dart
learnify/mobile/lib/product/theme/dark_theme.dart
learnify/mobile/lib/product/theme/light_theme.dart

As we have already talked about in the lectures and Suzan Hoca highlighted, annotations are the key part of the app. I was the responsible person to create the annotatable text widget to use in the required places (like chapter content). This PR will enable users to annotate texts inside the app.
------
1. Implementation of the annotatable text widget
2. Implementation of custom annotatable item
3. SelectionControlType enum
4. CustomTextSelectionControls by extending MaterialTextSelectionControls
5. Custom text selection toolbar implementation
6. Annotate dialog (when clicking to annotate text action)
7. Annotate text action callback integrated to the dialog
------
Closes #505.

Mobile: Annotatable Text Widget Implementation

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/core/widgets/dialog/dialog_builder.dart
learnify/mobile/lib/core/widgets/dialog/single_choose_dialog.dart
learnify/mobile/lib/core/widgets/text/annotatable/annotatable_text.dart
learnify/mobile/lib/core/widgets/text/annotatable/custom_text_selection_controls.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/profile/view/profile_screen.dart
learnify/mobile/lib/product/language/language_keys.dart

This PR is an enhancement of the annotation feature, specifically to PR #547. It implements a generic single choose dialog and integrates this into the overlapped annotation text parts to enable users to select a specific annotated text.
------
1. Implementation of a private annotatable text item model
2. Implementation of the generic single-choose dialog
3. Helper function to detect the annotations which contain the text that is clicked
4. Enhancement of overlapped annotation finder logic
5. Fix of overflow error in the text selection related to the wrong index numbers
6. Implementation of annotation selection callback
------
Closes #546

Mobile: Implementation of Multiple Annotation Selection Dialog - 546

---

learnify/backend/api/controllers/categories/get_categories.js
learnify/backend/api/controllers/categories/index.js
learnify/backend/api/controllers/learning_space/post_learning_space.js
learnify/backend/api/routes/categories.js
learnify/backend/api/routes/index.js
learnify/backend/api/validators/learning_space_init_validator.js
learnify/backend/models/categories.js
learnify/backend/models/categories.json
learnify/backend/models/index.js
learnify/backend/models/learning_space.js
learnify/backend/test/post_learning_point.test.js

I added categories logic to our backend, now during learning space creation, categories MUST be set.
------
1. Get /categories implemnetation
2. Post /learningspace adjusted to categories
------
Closes #551

get categories endpoint implementation and categories logic in learning spaces

---

learnify/mobile/lib/core/managers/navigation/navigation_manager.dart
learnify/mobile/lib/core/managers/navigation/navigation_route.dart
learnify/mobile/lib/features/auth/login/view-model/login_view_model.dart
learnify/mobile/lib/features/auth/login/view/login_screen.dart
learnify/mobile/lib/features/auth/signup/view-model/signup_view_model.dart
learnify/mobile/lib/features/auth/signup/view/signup_screen.dart
learnify/mobile/lib/main.dart
learnify/mobile/pubspec.yaml

This PR integrates the page transition animation for the navigation between the screens. It is integrated into our navigation manager by adding a navigation observer.
------
1. Integration of the page transition package
2. Implementation of the custom navigation observer to store the navigation stack
3. Helper methods to check navigation history items
4. Dynamic and customized page transition type check
------
Closes #558

Mobile: Page Transition Animation - #558

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/core/managers/navigation/navigation_route.dart
learnify/mobile/lib/features/home-view-all/view/view_all_screen.dart
learnify/mobile/lib/features/home/components/course_preview.dart
learnify/mobile/lib/features/home/view-model/home_view_model.dart
learnify/mobile/lib/features/home/view/home_screen.dart
learnify/mobile/lib/product/constants/navigation_constants.dart
learnify/mobile/lib/product/language/language_keys.dart

I have completed the view all screen. Seen learning spaces are dummy. When the backend side is done, these will be dynamic. Also view all button is now active all the time. When backend done its job, i will change buttons activation according to a number of the learning spaces. If it is greater than 8, it will be activated. Additionally, sinc courses are passed from the home page, there is no need to backend connection. For now, it is ready to be reviewed.
------
1. View all button is added to home screen
2. View all page is implemented
3. Navigation between pages is done
------
Closes #487

Mobile: Implementing View All Screen

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/core/extensions/number/number_extensions.dart
learnify/mobile/lib/core/managers/network/models/any_model.dart
learnify/mobile/lib/features/home/view-model/home_view_model.dart
learnify/mobile/lib/features/learning-space/models/event.dart
learnify/mobile/lib/features/learning-space/service/learning_space_service.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_item.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_list.dart
learnify/mobile/lib/features/learning-space/view/components/events/event_item.dart
learnify/mobile/lib/features/learning-space/view/components/events/events_list.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart
learnify/mobile/lib/main.dart
learnify/mobile/lib/product/language/language_keys.dart
learnify/mobile/pubspec.yaml

This PR includes the changes related to the events section in the learning space detail screen. It contains changes for the events lists, event items, random user data, event models, and fake event data.
------
1. Creation of event model with all helper functions (copyWith, dummy, fromJson, toJson)
2. Implementation of the event list inside the sliver
3. Integration of the intl package for formatting dates
4. Implementation of a basic event item as an expandable widget
5. Implementation of event detail title and description
6. Implementation and formatting of the event date
7. Implementation and formatting of the event duration
8. Integration of the random users API
9. Implementation of the user images row for event participants
10. Implementation of the participant number/participant …

Mobile: Learning Space Events Section - 583

---

learnify/backend/api/controllers/learning_space/index.js
learnify/backend/api/controllers/learning_space/post_create_post.js
learnify/backend/api/routes/learning_space.js
learnify/backend/api/validators/learning_space_init_validator.js
learnify/backend/models/learning_space.js
learnify/backend/models/post.js

This PR includes post model and creating post endpoint. Please do check the postman documentation for it:
https://documenter.getpostman.com/view/16983185/2s8Yt1tADd#d8ae5b85-8393-4f6d-870b-3165c89ddb16
------
1.Post model
2. Create post endpoint
------
Closes #(589)

Backend: Create post endpoint implemented

---

learnify/mobile/lib/core/widgets/measured_size.dart
learnify/mobile/lib/features/learning-space/view/create_learning_space_screen.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart
learnify/mobile/pubspec.yaml
learnify/mobile/test/chapter_test.dart
learnify/mobile/test/test_helpers.dart

This PR will fix the chapter unit test error due to the package dependency added by Egemen for dynamically sized widgets. It both implements our own logic for dynamically sized widgets and also adjusts tests according to the recent updates in the learning space detail screen.
------
1. Remove measured size package dependency
2. Implement our own logic
3. Fix the bug that produces errors while testing
4. Adapt the tests to the recent changes made in the lesson detail screen
------
Closes #598

Mobile: BugFix - Chapter Unit Tests

---

learnify/mobile/lib/core/constants/main_type_definitions.dart
learnify/mobile/lib/core/widgets/text/annotatable/annotatable_text.dart
learnify/mobile/lib/core/widgets/text/annotatable/custom_annotatable_item.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/test/annotation/text_annotations_test.dart

This PR includes the implementation of the tests for the text annotation feature.
------
1. Create a type definition for annotating callback
2. Separate text annotation creation logic from the service request 
3. Separate image annotation creation logic from the service request
4. Implement widget finder tests
5. Implement annotation creation test
6. Check the existence of the annotation after the creation
------
Closes #606

Mobile: Text Annotation Tests - 606

---

learnify/mobile/lib/core/widgets/image/annotatable_image.dart
learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_item.dart
learnify/mobile/lib/features/learning-space/view/components/chapter_image.dart
learnify/mobile/test/annotation/image_annotations_test.dart

This PR includes the implementation of the tests for the image annotation feature.
------
1. Implement widget finder tests
2. Implement image annotation creation test
3. Check the existence of the annotation after the creation
------
Closes #608

Mobile: Image Annotation Tests - 608

---

learnify/web/src/pages/LearningSpace.js

Back-end connection & modularization of LS page.
------
1. Providing back-end connection, using the related end-point 
2. Modularization of LS page.
------
Closes #625

Dev frontend backend of ls

---

learnify/web/src/pages/CreateLS.js
learnify/web/src/pages/EmailVerificationPage.js
learnify/web/src/pages/LearningSpace.js

------
The connection and parameter transfer between create ls page and ls page is done. Can be tested via creating ls and it will automatically direct you to the created ls page.

Frontend: interconnection between the create ls and ls page is done is done

---

learnify/web/src/pages/LearningSpace.js

------
Hotfix for the modular router of Learning Space.

Router modularization fixed.

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/forum_list.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart
learnify/mobile/lib/product/language/language_keys.dart

implements discussion screen with random mock data
------
1. Learning Space Forum segment UI implementation
2.  Randomized mock discussion data 
------
Closes #620

Mobile: LS Forum 

---

learnify/backend/api/controllers/learning_space/get_by_creator.js
learnify/backend/api/controllers/learning_space/get_by_participation.js
learnify/backend/api/controllers/learning_space/index.js
learnify/backend/api/routes/learning_space.js

This PR includes 2 endpoints:
GET /learningspace/user/participated: returns the learningspaces user is participating in.
GET /learningspace/user/created: returns the learning space user has created.
As getting learning spaces of another user is not included in this milestone, that part is not implemented.
Closes #619

GET endpoints regarding user and learningspace relation

---

learnify/mobile/test/taken_ls_screen_test.dart
learnify/mobile/test/view_all_screen_test.dart

I have implemented widget tests for view all screen and taken learning spaces screen using view all list since these two screens call this widget.
------
1. Test view all screen which is accessed from home page
2. Test taken learning spaces screen which is accessed from navigation bar
------
Closes #646

Mobile: Tests for Pages Which Use View All List

---

learnify/web/src/App.js
learnify/web/src/components/LearningSpaceDetailBox.js
learnify/web/src/components/Participants.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/LearningSpace.js

For the section of participants in the learning space page; the box component was created, different icons for the creator contributor and participating contributors were selected, back-end connection was made.
------
1. Participants Component.
2. Participants' back-end connection.
3. Hotfixes for slight issues.
------
Closes #648

Dev frontend ls participants

---

learnify/web/src/components/JoinLsButton.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/EmailVerificationPage.js
learnify/web/src/pages/LearningSpace.js
learnify/web/src/pages/LoginForm.js

Join functionality on a Learning Space is implemented via its backend connection and implemented as a component which is modular and implements a control logic to check if a user is already enrolled or not.
------
Closes #656

Frontend: Join Learning Space

---

learnify/web/package-lock.json
learnify/web/src/components/NavBar.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/style.css

I have implemented the semantic search component of our web application's frontend. It is a part of the `<NavBar/>` component and backend connection between the component and the search endpoint is established. The general design of the component complement the general design theme of our application.
When user prompts an input, results are displayed as a dropdown list, each item is clickable and redirects the user to the respective page of the search result.
***
* As of now, our semantic search endpoint only provides results of learning spaces. When other parts of our application is completed, such as users, profiles etc. the semantic search will be enhanced accordingly and our web application's search component will also be updated accordingly.
***
***
Closes #652

Frontend: Semantic Search Bar Implementation

---

learnify/backend/test/put_edit_post.test.js

This PR includes the unit tests for PUT edit post endpoints.
------
1. Unit test file for the related endpoint
------
Closes #(665)

Backend: Unit Tests for Edit Post Endpoint

---

learnify/backend/test/post_create_post.test.js

This PR includes the unit test for POST create post endpoint.
------
1. Unit test file for the related endpoint.
------
Closes #(663)

Backend: Create Post endpoint Unit Test

---

learnify/web/package-lock.json
learnify/web/package.json
learnify/web/src/components/Post.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/LearningSpace.js
learnify/web/src/pages/style.css

Annotations are among the main components of our application, as we have previously discussed in the lectures and Suzan Hoca has underlined. As of last week, we were unsure of exactly how to incorporate annotations in the web component and we were unable to locate many examples. However, I have managed to put the image and text annotations to use beneath the learning space in accordance with the decisions and responsibility divisions we decided upon in our frontend team meeting, so, post images and text contents are now annotatable.
------
1. Determining the way/logic that will be used to create image and text annotations
2. Implementing a generic annotatable image and text tool to use across the app
3. Integrating annotatable image and text tool into post content
4. Testing annotation …

Frontend: Implementation of the Text and Image Annotation

---

learnify/web/src/components/Post.js
learnify/web/src/pages/LearningSpace.js
learnify/web/src/pages/style.css

We needed to have a page component where co-learners can edit existing posts which are located in learning space posts section.
The created component includes three input fields, one for entering the title of post and one for entering the image url for the post, and the final one for entering the contents of the post. While editing an existing post, these input fields contains the existing post's data.
Finally, there is a submit button indicating that editing is done.
In addition to above mentioned parts, I have prepared edit post section of the learning space page and now it does send post request to our backend service to edit the related post. We are now providing the backend connection to edit post component so that proper requests can be sent and edited posts can be put to our …

Frontend: Implementation For Edit Post Feature and Backend Connection

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md
deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

I have created a new folder inside the "deliverables" folder called "CMPE451_Customer_Presentation_Milestone_2" as instructed in the Customer Milestone 2 Deliverables guidelines. I have included the related hyperlinks in the "deliverables.md" and "group_review.md" files.
In addition, each member of our team will list their contributions on separate pull requests in the format provided under the heading "Individual Contributions Report." Each team member will also add the sections they are in charge of to the group review document in a proper format considering the Customer Milestone 2 Deliverables guidelines and the division of labor we made in our group meeting on Monday, December 5th.
------
1. Creating the "CMPE451_Customer_Presentation_Milestone_2" folder
2. Creating the …

Milestone 2: Preparing Deliverables and Group Review

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

I have added my individual milestone to the deliverables.md file.

Milestone-2 Report: My Individual Milestone

---

learnify/web/package-lock.json
learnify/web/package.json
learnify/web/src/__tests__/NotFoundPage.test.js
learnify/web/src/__tests__/__snapshots__/NotFoundPage.test.js.snap
learnify/web/src/pages/NotFoundPage.js

The other components of our web application influenced how the not found page was developed. Because of this, by the second customer demo, it was not ready for a unit test. Since the not found page is now finished, we must use unit tests to test it before finishing it entirely.
I have implemented unit tests for the not found page and you could see the shared results from related issue.
------
1. Tested the page snapshot
2. Tested if components are rendered correctly
3. Shared results
------
This PR is linked to the issue https://github.com/bounswe/bounswe2022group2/issues/681

Frontend: Unit Tests for Not Found Page

---

learnify/web/src/__tests__/Footer.test.js
learnify/web/src/__tests__/__snapshots__/Footer.test.js.snap

This PR includes the implementation of unit tests for the Footer component. Further information can be acquired via related [issue](https://github.com/bounswe/bounswe2022group2/issues/686).
------
Closes #686

Implementation of Unit Tests for the Footer Component.

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Annotations section updated according to the status of our application, frontend, mobile and backend.
------
1. Status of the Annotations
2. Standarts followed by W3C
3.  Future Improvements
------
Closes #675

Milestone-2 Report: Annotations

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

This PR includes my individual contribution report to the milestone-2 deliverables.md.
------
Closes #691

Milestone-2 Report: Individual Report in Deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Issues, PRs and my contributions are added to the group-review.md
------
1. Issues and PRs
2. My individual report
------
Closes #691

Milestone-2 Report: Individual Report and Issue & PR Links

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

I have added my contributions.

Individual contribution & PR/issue Information

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

I have added my individual sections to the report.
------

Individual report Koray's parts

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

This PR includes the additions I did for the UI/UX section in the milestone 2 reports. Since I am a part of the mobile team, I will add the designs/screens I implemented as it is mentioned in #710 
------
1. Add the screens/designs implemented by me
2. Add the corresponding screenshots
3. Add the code link
4. Add an explanation if needed
------
Related to #710

Milestone 2: Mobile UI/UX Section - Bahrican

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

This pull request is opened to add @egemenatikk's individual report to general group report.
------
1. @egemenatikk's individual report
------

Milestone-2: Egemen's individual report

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Summary of work and individual contributions for milestone report.
------
Closes #696

Ezgi individual contibutions

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

There were some errors and missing parts of the previous version of my individual contributions. I have fixed the tabular format and pull requests links. I have also added the unit tests from Milestone 1, which is needed to include in this report
------
1. Fix of the individual contributions

Update my individual contributions

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

add mobile screens for the UI section for the following screens:
- forget password
- create learning space
- discussion forum
- annotation details

add mobile screens

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

This pull request is opened to add @egemenatikk's individual contributions table and report to general group report.
------
Closes #706

Egemen's individual contribution table and report are added

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

API Documentation for implemented endpoints is needed for Milestone-2 Report.
------
1. Postman link for documentation
2. Documentation for: Create Post, Edit Post, Create Annotation, Edit Annotation, Enroll to Learning Space
3. Short summary
------
Closes #677

Milestone-2 Report: API Documentation

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

The deliverables and their progress should be stated in the group review section of Milestone 2 report. The group determined that a tabular format makes this the most understandable. I have compiled this list and included it in the group review report.
------
1. Creating a table in the report
2. Filling the deliverables and their status
3. Add hyperlinks
------
This PR is linked to the issue https://github.com/bounswe/bounswe2022group2/issues/712

Milestone-2 Report: List and Status of Deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

My personal contributions for the milestone report

batuhan celik personal contribution

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

I have added my individual contributions report to the group's second milestone report
------
Closes #714

Milestone-2: Contribution report - Onur

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md

The individual contribution report of @surmelienes1 has been documented, as was suggested in https://github.com/bounswe/bounswe2022group2/issues/668. My evaluation of our second demo, the unit tests I have so far developed, and the issues and pull requests I have created for Milestone-2 are all included in the report.
------
1. Linking issues and pull requests
2. Include unit tests
3. Responsibilities
4. Main contributions
5. Significant issues
6. Summary of Individual Work" table
------

Milestone 2: Individual Report

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Executive Summary
This is a PR for adding an executive summary of Learnify to the Milestone-2 report.
Related issue #704

Executive Summary

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Added my part of the web application's UI designs.

Milestone-2: Web Application's UI Designs - Altay

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Added my part of the web application's UI designs.

Milestone-2: Web Application's UI Designs - Gökay

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

I have filled my summary of work table for milestone 2. Addition to that I have fixed minor issues of the document.
------
Closes #714

Milestone-2: Summary of work - Onur

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md
deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

This PR includes the additions for mobile in the annotations section of the group review file.
------
1. Update on status info for mobile
2. Update on standards info for mobile
3. Addition of mobile code screenshot and description
4. Addition of mobile app feature demonstration screenshots
5. Addition on future improvements part for mobile
------
Closes #719

Milestone 2: Mobile Related Additions to the Annotations Part

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

my PR table with time consumption for the group review

add time consumption table

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

I have added the two pages, I was responsible for during the design and the implementation.
------
1. LS page UI
2. Login Page UI
------

Update group_review.md UI's

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

I have added the user interface screenshots that I did, and related codes are linked. 
------

Milestone-2: Mobile User Interface - Onur

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

This pull request is opened to add progress according to requirements part to general group report for milestone 2.
------
Closes #705

Milestone-2 : Progress according to to requirements

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Time consumptions for issues and PRs for my work added.
------

Milestone-2 Report: Time Consumption of my Individual Work

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Milestone-2: Added time tracking

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md
deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Added missing unit tests and fixed pr links in deliverables.md

Milestone-2: Update on my individual part

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Added my part of the web application's UI designs.
------
Related with the issue #723

Milestone-2: Web Application's UI Designs - Enes

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Time consumption for issues and PRs for my work added.
You can also see my weekly efforts [here](https://github.com/bounswe/bounswe2022group2/wiki/Bahrican-Yesil#weekly-workcontribution---cmpe-451).

Milestone 2: Individual Work Wime Tracking - Bahrican

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Added status of deliverables as it is right now, since the deadline is close.
------
Closes #718

Milestone-2: Status of Deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_2/deliverables.md
deliverables/CMPE451_Customer_Presentation_Milestone_2/group_review.md

Time consumption for issues and PRs for my work added.
You can also see my weekly efforts [here](https://github.com/bounswe/bounswe2022group2/wiki).

Milestone 2: Individual Work Wime Tracking - Enes

---

learnify/mobile/test/settings/settings_test.dart

I have already implemented settings screen with PR #760. This PR includes the tests of the implemented settings screen.
------
1. Test settings item list finder
2. Test the number of settings item
3. Test the type of each setting item
4. Test expansion tile existences
5. Test theme switch existence in the expected place
6. Test the dark theme preference
7. Test language options
8. Test correctness of the selected language
9. Test theme switch functionality
------
Closes #768

Mobile: Tests - Settings Screen

---

learnify/web/src/components/LearningSpacePrev.js
learnify/web/src/pages/HomePage.js
learnify/web/src/pages/style.css

I have established the backend connection between the my learning spaces part of our home page and our REST API. The page once featured filler data. Now, a user can browse the learning spaces that they are participating (contributing) in via the related part of the page. Each prev box component is clickable and redirects the user to the related learning space page.
***
* The endpoint that is used was /learningspace/user/participated.
* It requires token based authentication.
* Every participated learning space is now accessible from that part of the home page, yet it is contained in a small scrollable area. 
***
***
Closes #791

Frontend: Home Page My Learning Spaces Backend Connection

---

learnify/web/src/pages/HomePage.js
learnify/web/src/pages/style.css

I have established the backend connection between the popular learning spaces part of our home page and our REST API. The page once featured filler data. Now, a user can browse the 10 most popular learning spaces via the related part of the page. Each prev box component is clickable and redirects the user to the related learning space page.
***
* The endpoint that is used was /learningspace. It returns every learning space sorted by popularity, i.e. number of participants.
* It requires token based authentication.
* It only shows 10 most popular learning spaces.
***
***
Closes #792

Frontend: Home Page Popular Learning Spaces Backend Connection

---

learnify/web/src/App.js
learnify/web/src/pages/HomePage.js
learnify/web/src/pages/MyLearningSpacesPage.js
learnify/web/src/pages/style.css

I have implemented the my learning spaces page. It is an independent page and can be reached from the related view all button on the home page. The page makes a GET request to the backend to retrieve the list of learning spaces that a user participates in, and then displays them in a series of "LearningSpaceDetailBox" components. The page also includes a NavBar and Footer component. The page makes use of React's useState and useEffect hooks to manage state and perform the GET request when the page is loaded. The page also retrieves the user's username from local storage and displays it in the page header.
***
* The endpoint that is used was /learningspace/user/participated.
* It requires token based authentication.
* Each learning space detail box featured in the page is clickable and …

Frontend: My Learning Spaces Page

---

learnify/web/src/components/ProfilePhoto.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js

Profile photo component has been created and added into the profile page 
------
Closes #795

Frontend: profile photo component

---

learnify/web/src/components/AboutUser.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js

Bio component implemented and putted under profile page
Closes #824

Frontend: Dev frontend profile page bio

---

learnify/mobile/lib/features/home/components/course_preview.dart
learnify/mobile/lib/features/home/view/home_screen.dart
learnify/mobile/lib/features/learning-space/models/learning_space_model.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/events/event_item.dart
learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart

This PR integrates participants field and displays a dialog for the participants of a learning space.
------
1. Integrate participants into the learning space model
2. Display dialog on participants click

Mobile: Clickable Learning Space Participants

---

learnify/web/src/components/UserNameProfile.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js

User name component has been generated, detailed description is provided in the related [issue](https://github.com/bounswe/bounswe2022group2/issues/836)
------
1. Implementation of the user name component and modularization of the related part in the profile page. 
2. Related CSS component for the user name section in the profile pages.
------
Closes #836

Dev frontend user name component

---

learnify/web/src/components/AboutUser.js
learnify/web/src/components/ProfilePhoto.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js

backend connecion of profile page and connection for bio component
------
Closes #837

Frontend: connection of bio component

---

learnify/annotations-service/backend/.env.prod
learnify/backend/api/controllers/user/get_search_users.js
learnify/backend/api/controllers/user/index.js
learnify/backend/api/routes/user.js

This pull request adds a new endpoint to the User Search API, located at /user/search. The endpoint allows users to search for other users by their usernames. It takes a path parameter, username, which is used to filter the search results to only include usernames that include the given parameter.
The endpoint returns an array of usernames that match the search criteria
------
1. User search API implementation
------
Closes #(845)

Backend: User Search API

---

learnify/web/src/components/ProfilePhoto.js
learnify/web/src/pages/ProfilePage.js

Showing the profile picture and uploading a profile picture in the base64 format is provided
To try and test please upload a profile picture and click on the picture an upload a new one change page and return the profile
------
Closes #837

Dev frontend profile page profile photo

---

learnify/web/src/components/LearningSpaceDetailsProfile.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js
learnify/web/src/pages/style.css

This PR includes the creation of the participated LS's component for the profile page and also the connection to the backend of this component.  Detailed information and process stages can be acquired via related [issue](https://github.com/bounswe/bounswe2022group2/issues/851)
------
Closes #851

Dev frontend profile page ls component

---

learnify/web/src/App.js
learnify/web/src/components/NavBar.js
learnify/web/src/components/Participants.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js

Navbar and participants components are updated to access the related users profiles from the names and profile page url is updated to show username in it.
Closes #844

Frontend: profile page connections

---

learnify/web/src/components/Comment.js
learnify/web/src/components/Post.js

The implementation of a comment feature for the learning space page has been completed, and the necessary backend integration has now been implemented in order to facilitate the sending of requests for the creation and retrieval of comments.
Specifically, it was necessary to establish a connection with the backend service in order to facilitate the submission of POST requests for the creation of new comments, as well as the sending of GET requests to retrieve existing comments from the database.
In order to ensure the functionality of this feature, it was imperative that the backend integration has been implemented in a technically sound manner, adhering to proper coding practices and standards. I succesfully accomplished my duty to complete this task as described above.
------
1. …

Frontend: Backend Connection For Create and Get Comment

---

learnify/web/src/components/AboutUser.js
learnify/web/src/components/component_styles.css
learnify/web/src/pages/ProfilePage.js
learnify/web/src/pages/style.css

This is a revision PR detailed explanation has been provided via related [issue](https://github.com/bounswe/bounswe2022group2/issues/856)
------
1. Profile page and components inside modification.
2. CSS file additions and revisions.
------
Closes #856

Dev frontend update profile

---

learnify/backend/test/post_auth_signup.test.js
learnify/backend/test/post_event.test.js
learnify/backend/test/post_learning_point.test.js
learnify/backend/test/post_participate_event.test.js

As we have continued development, the endpoints have changed and some tests that previously implemented by me were not working correctly due to those changes.
This PR is about updating those tests so that they are functioning correctly.
------
1. Update tests so that they comply with current API 
2. Increased database mocking so that tests do not exceed time constraints imposed by mocha
3. Added randomization to the key fields, this allows tests to be runnable many times using the same in memory database.
------

Revision of tests : POST /auth/signup , POST /learningspace, POST /events, POST /events/participate/:eventId

---

learnify/mobile/lib/features/learning-space/models/event/create_event_request.dart
learnify/mobile/lib/features/learning-space/service/l_ls_service.dart
learnify/mobile/lib/features/learning-space/service/ls_service.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/events/events_list.dart
learnify/mobile/lib/features/learning-space/view/create_event_screen.dart

This pull request is opened to merge backend connection of create event screen to our application.
------
1. Fixing in the create event request model
2. Implementation of backend connection function
3. Implementation of functions that triggers backend connection functions
4. Fixing "done" button not being active in the create event screen
------
Closes #873

Mobile: Create event backend connection

---

learnify/backend/api/controllers/learning_space/get_reccomended.js
learnify/backend/api/controllers/learning_space/index.js
learnify/backend/api/controllers/learning_space/semantic_search_learning_space.js
learnify/backend/api/routes/learning_space.js
learnify/semantic_service/main.py

Implementation of learning space recommendation in backend
------
1. An endpoint on backend to get 10 recommended learning spaces
2. An endpoint on semantic server to get 10 recommended learning spaces
3. Handling the edge case: empty query in the semantic search endpoint
4. Additional logging for the semantic search endpoint
------
Closes #888

learning space recommendation endpoint

---

learnify/web/src/components/AboutUser.js
learnify/web/src/components/ProfilePhoto.js
learnify/web/src/pages/ProfilePage.js

Detailed description can be found in the related [issue description](https://github.com/bounswe/bounswe2022group2/issues/877)
------
1. Profile Page and About Info, Profile Page components change.
------
Closes #877

Dev frontend profile page edit

---

learnify/web/src/components/Comment.js
learnify/web/src/components/Post.js

The implementation of the upvote and downvote feature for the learning space page has been completed, and the necessary backend integration has now been implemented in order to facilitate the sending of requests for the upvote or downvote incrementation and retrieval of existing number of upvotes and downvotes.
Specifically, it was necessary to establish a connection with the backend service in order to facilitate the submission of POST requests for the upvote or downvote incrementation, as well as the sending of GET requests to retrieve existing number of upvotes and downvotes from the database.
In order to ensure the functionality of this feature, it was imperative that the backend integration is implemented in a technically sound manner, adhering to proper coding practices and …

Frontend: Backend Connection for Upvote and Downvote Functionality for Posts and Comments

---

learnify/web/src/components/Footer.js

I have updated the footer component of the React Learnify application to enhance navigation for users. The revised component allows for seamless navigation to desired pages, regardless of the current location within the application. This update aims to improve the user experience and convenience of navigating within the app.
------
1. Updated footer component of our web part of the application
2. Easy navigation between places inside the application

Frontend: Fixing the Footer Navigation

---

learnify/web/src/components/Comment.js
learnify/web/src/components/Post.js
learnify/web/src/components/component_styles.css

The implementation of the editing comment feature for the learning space page has been completed, and the necessary backend integration has now been implemented in order to facilitate the sending of requests for the editing comments and retrieval of updated comments.
Specifically, it was necessary to establish a connection with the backend service in order to facilitate the submission of POST requests for the editing comment feature, as well as the sending of GET requests to retrieve updated comments from the database.
In order to ensure the functionality of this feature, it was imperative that the backend integration has been implemented in a technically sound manner, adhering to proper coding practices and standards. I successfully completed my duty to accomplish this task as described …

Frontend: Backend Connection for Editing Comments of Learning Space Posts

---

learnify/web/src/pages/HomePage.js

I have implemented recommended learning spaces feature in `HomePage` component. This feature fetches a list of recommended learning spaces for the logged in user from the backend and displays them in the user interface. The recommended learning spaces are fetched using a GET request to the `/learningspace/user/recommended` endpoint and are displayed in the user interface using the `LearningSpacePrev` component. The recommended learning spaces are displayed in the same way as the other learning spaces in the user interface.
***
* The endpoint used for user search is `/learningspace/user/recomended`
***
***
Closes #900

Frontend: Recommended Learning Spaces in Home Page

---

learnify/web/src/__tests__/ContactPage.test.js
learnify/web/src/__tests__/NavBar.test.js
learnify/web/src/__tests__/__snapshots__/ContactPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/LSbyCategoryPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/MyLearningSpacesPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/NavBar.test.js.snap
learnify/web/src/__tests__/__snapshots__/PopularLearningSpacesPage.test.js.snap
learnify/web/src/pages/ContactPage.js

Contact Page unit tests implementation, related [issue](https://github.com/bounswe/bounswe2022group2/issues/893)
------
1. Addition of various test IDs to the Contact Page.
2. Unit tests for the Contact Page.
3. Snapshot changes according to the latest implementations for testing.
------
Closes #893

Dev frontend contact page unit test

---

learnify/web/src/__tests__/ContactPage.test.js
learnify/web/src/__tests__/LearningSpaceDetailsProfile.test.js
learnify/web/src/__tests__/NavBar.test.js
learnify/web/src/__tests__/__snapshots__/ContactPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/LSbyCategoryPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/LearningSpaceDetailsProfile.test.js.snap
learnify/web/src/__tests__/__snapshots__/MyLearningSpacesPage.test.js.snap
learnify/web/src/__tests__/__snapshots__/NavBar.test.js.snap
learnify/web/src/__tests__/__snapshots__/PopularLearningSpacesPage.test.js.snap
learnify/web/src/components/LearningSpaceDetailsProfile.js

This PR includes the implementation of the unit tests for Profile Page User LS's Component, also the related issue is #898. 
------
1. Implementation of the unit tests for the mentioned component.
2. Data Test ID additions to the related component file for testing reasons.  
------
Closes #898

Dev frontend participated ls profile component unit tests

---

learnify/web/src/components/Comment.js
learnify/web/src/components/Post.js
learnify/web/src/components/component_styles.css

We have added links to the usernames in both the posts and comments sections of our application. These links redirect the user to the profile page of the related user when clicked.
This change improves the user experience by making it easier for users to navigate to other user's profiles and view their content. It also makes our application feel more interactive and connected.
To implement this feature, we modified the frontend code that displays the posts and comments and added a link element around the username. We also updated the backend to handle requests to the user profile pages and serve the appropriate content.
------
Closes #901 #903

Frontend: comment and post link added to user

---

learnify/web/src/App.js
learnify/web/src/components/Footer.js
learnify/web/src/pages/HomePage.js
learnify/web/src/pages/RecommendedLearningSpacesPage.js
learnify/web/src/pages/style.css

I have implemented the popular learning spaces page for our web application. This pull request adds a new page called `PopularLearningSpacesPage` which displays a list of recommended learning spaces to the user. The learning spaces are fetched from the backend API by making a GET request to the `/learningspace/user/recomended` endpoint with the user's authorization token. The learning spaces are then displayed to the user using the `LearningSpaceDetailBox` component. The page also includes the `NavBar` and `Footer` components.
I have also included a `style.css` file to handle styling for the page.
***
* The endpoint used for user search is `/learningspace/user/recomended`
* The endpoint uses token for authorization.
***
***
Closes #906

Frontend: Recommended Learning Spaces Page

---

learnify/mobile/lib/features/learning-space/models/post_model.dart

This PR is a hotfix for failing tests because of the change made in the dummy post constructor.
------
1. Add a dummy image list for the dummy post constructor

Mobile: Hotfix annotation tests carousel slider

---

learnify/mobile/lib/features/learning-space/service/l_ls_service.dart
learnify/mobile/lib/features/learning-space/service/ls_service.dart
learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart
learnify/mobile/lib/features/learning-space/view/components/events/event_item.dart

This pull request is opened to merge backend connection of attend event functionality to our application.
------
1. Implementation of backend service function for attend event functionality
2. Implementation of view model function for attend event functionality
3. Handling of state management
------
Closes #911

Mobile: Attend event backend connection 

---

learnify/mobile/assets/lang/en.json
learnify/mobile/lib/features/home/service/I_home_service.dart
learnify/mobile/lib/features/home/service/home_service.dart
learnify/mobile/lib/features/home/view-model/home_view_model.dart
learnify/mobile/lib/features/home/view/home_screen.dart
learnify/mobile/lib/features/search/view-model/search_view_model.dart
learnify/mobile/lib/product/language/language_keys.dart

This pull request is opened to merge revisions made in home screen to our mobile application.
------
1. Implementation of backend function for getting recommended learning spaces
2. Implementation of home view model function for getting recommended learning spaces
3. Fixing titles of learning space types in the home screen
4. Fixing the initial learning space list in the search screen
------
Closes #916

Mobile: Home screen revision

---

learnify/web/src/components/Post.js

The connection is provided between the frontend and backend to show and post the annotations
------
Closes #918

Frontend: Dev frontend annotation be connection

---

learnify/mobile/lib/features/profile/view-model/profile_view_model.dart
learnify/mobile/lib/features/profile/view/profile_screen.dart

Before that PR, update profile button didn't working. However, it is working properly now. 
------
1. Fix of the major update profile bug
------

Mobile: Profile Update Major BugFix

---

learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart

This PR is a hotfix for changing deployed URL of the web app.
------
1. Fix the source base URL in the annotation model
2. Add missing '/' character

Mobile: Hotfix annotation source base url

---

learnify/mobile/assets/lang/de.json
learnify/mobile/assets/lang/es.json
learnify/mobile/assets/lang/ja.json
learnify/mobile/assets/lang/ko.json
learnify/mobile/lib/features/learning-space/view/create_event_screen.dart

This pull request is opened to merge a hotfix to our mobile application.
------
1. Translation of newly added words
2. Fixing of small overflow

Translate newly added words

---

learnify/mobile/lib/core/providers/provider_list.dart
learnify/mobile/lib/features/profile/view-model/profile_view_model.dart
learnify/mobile/lib/features/profile/view/profile_screen.dart

Please include a summary of the changes exist in this PR and the reasons to merge this PR.
------
1. Fix of the signup screen form bug
2. Search screen implementation
------

hotfix - fix profile username

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

I have created a new folder inside the "deliverables" folder called "CMPE451_Customer_Presentation_Milestone_3" as instructed in the Customer Milestone 3 Deliverables guidelines. I have included the related hyperlinks in the "final_deliverables.md" file.
In addition, each member of our team will list their contributions on separate pull requests in the format provided under the heading "Individual Contributions Report." Each team member will also add the sections they are in charge of to the group review part in a proper format considering the Customer Milestone 3 Deliverables guidelines and the division of labor we made in our group meeting on Friday, December 30th.
------
1. Creating the "CMPE451_Customer_Presentation_Milestone_3" folder
2. Creating the "final_deliverables.md" file …

Milestone 3: Preparing Final Deliverables

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

This PR includes the changes regarding the final milestone report. The related sections mentioned below, under the "What Does This PR Include?" title are filled and prepared by this PR.
------
It includes the filling of the contents for the following sections in the final milestone report:
------
Closes #936

Final Milestone: Executive Summary

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

This PR includes the additions to the summary of the work table in the final milestone for myself, Bahrican Yeşil. It will be consisting of all issues and pull requests from the beginning through the whole project.
------
1. Milestone 1 Issues
2. Milestone 2 Issues
3. Final Milestone 3 Issues
4. Milestone 1 PRs
5. Milestone 2 PRs
6. Final Milestone 3 PRs
------
Closes #939

Final Milestone: Summary of Work - Bahrican Yeşil

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

This PR includes the additions to the individual contributions report in the final milestone for myself, Bahrican Yeşil. It will be consisting of my responsibilities, main contributions, pull requests, unit tests, and additional information from the beginning through the whole project.
------
1. My Responsibilities
2. Main Contributions
3. Pull Requests
4. Unit Tests
5. Additional Information
------
Closes #938

Final Milestone: Individual Contributions Report - Bahrican Yeşil

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

This pull request is opened to merge adding SRS, UML diagrams, user scenarios and mockups to final milestone report.
------
1. Adding software requirements specification to final milestone report
2. Adding use-case, class and sequence diagrams to final milestone report
3. Adding user scenarios and mockups to final milestone report
------
Closes #946

Final milestone: Add software requirements specification, UML diagrams, user scenarios and mockups to report

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

all requirements are reviewed and have been updaten when necessary, all of the requirements are evaluated in terms of the progress we made throughout the fall semester and the point that we came.
------
Closes #944

Final milestone progress in requirements

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

I have filled my summary of work table part in final milestone report. 
------
Closes #958

Final Milestone: Summary of Work Table for Onur Kömürcü

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Release notes section for the final milestone report.

add release notes for the final milestone

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

includes personal contribution of Batuhan Celik for the final milestone

personal report for batuhan celik

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Added my own summary of work table with related links and description
------
Closes #973

Summary of Work Table: Altay Acar

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

UI/UX for previous pages have been checked and the related sections for the new ones are created.
UI/UX for previous pages have been checked and the related sections for the new ones are created.
------
1. Frontend new pages screenshots
2. Hyperlinks for the implementation of those pages
------
Closes #975

Frontend: UI/UX additions final milestone

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

The deliverables and their progress should be stated in the the status of the deliverables section of the final milestone report. The group determined that a tabular format makes this the most understandable. I have compiled this list and an explanation and included them in the final milestone report.
------
1. Creating a table in the report
2. Filling the deliverables and their status
3. Add hyperlinks
------
This PR is linked to the issue https://github.com/bounswe/bounswe2022group2/issues/950

Final Milestone Report: List and Status of Deliverables

---

learnify/web/src/__tests__/AboutUser.test.js
learnify/web/src/__tests__/__snapshots__/AboutUser.test.js.snap

Unit tests are initialized for AboutUser component and ProfilePhoto component.
------
Closes #929

Frontend: unit test initialized for bio and profile picture

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Every screen implemented on mobile and the web should be listed on the final report with screenshots and links to the code in the repository.  This includes the mobile screens
------
1. Mobile section of the User Interface / User Experience section
------

Final Milestone: UI/UX mobile screens

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Individual report for the final milestone.
------
1. Member efforts table
2. Individual contributions report
------
Closes #972

Final Milestone: add individual efforts - Ezgi

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Added individual contribution report for myself into the report.
------
Closes #959

Final Milestone: Individual Contributions Report for Onur Kömürcü

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

This pull request is opened to merge adding user manual to final milestone report.
------
1. Adding user manual to final milestone report
------
Closes #951

Add user manual

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

I have updated my individual contributions report.
------
Closes #977

Individual Contributions Report: Altay Acar

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Adds link of updated system manual to the final milestone report
------
Closes #961

Final Milestone : system manual

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

individual efforts by gokay
------
Closes #941

Final Milestone: individual effort by gokay

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

I have update project plan for the final milestone report. I am also added this update project plan to corresponding wiki page. Further details can be found under the report.
Closes #956

Final Milestone: Project Plan

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

The final Group Milestone Report had to include a summary of each team member's work in a table, which should be consistent with each member's Individual Contributions Report. Each team member was responsible for preparing their own summary of work. I completed the table for representing my summary of work.
------
1. Issue table - milestone 1
2. Issue table - milestone 2
3. Issue table - final milestone
4. PR table - milestone 1
5. PR table - milestone 2
6. PR table - final milestone
------
This PR is linked to the issue https://github.com/bounswe/bounswe2022group2/issues/949

Final Milestone: Summary of Work Table for Enes Sürmeli

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

The individual contribution report of @surmelienes1 had to be documented, as was suggested in https://github.com/bounswe/bounswe2022group2/issues/934. My evaluation of our final demo, the unit tests I have so far developed, and the issues and pull requests I have created for Milestone-3 and the first two milestones are now all included in the report.
------
1. Include member information
2. Link issues and pull requests
3. Include unit tests
4. Responsibilities
5. Main contributions
6. Significant issues
7. Additional information
------
This PR is linked to the issue https://github.com/bounswe/bounswe2022group2/issues/948

Final Milestone: Individual Contributions Report for Enes Sürmeli

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Individual contributions and summary of work added for Koray Tekin.
Individual contributions and summary of work added for Koray Tekin.
------
1. Individual Report Sections.
2. Summary of general work.
------
Closes #981

Personal Report, individual contributions Koray

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

contributions for gokay
------
Closes #942

gokay updates for personal contributions

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Please include a summary of the changes exist in this PR and the reasons to merge this PR.
------
1. Fix of the signup screen form bug
2. Search screen implementation
------

Final milestone/individual contributions egemen atik 988

---

deliverables/CMPE451_Customer_Presentation_Milestone_3/final_deliverables.md

Please include a summary of the changes exist in this PR and the reasons to merge this PR.
------
1. Fix of the signup screen form bug
2. Search screen implementation
------

Added mobile app scenario
