practice-app/server/src/api/controllers/category/createCategoryEndpoint.js
As POST /api/category (This endpoint imports a title and converts it to a category) is implemented in #165, I forgot to send a bad request return code when a title is not given.
Made the necessary changes and now it is functional.
=> HOTFIX: POST /api/category, adding no title is given to bad request cases

practice-app/server/src/api/controllers/lesson/get_lesson_events.js, practice-app/server/src/api/controllers/lesson/index.js, practice-app/server/src/api/routes/lesson.js, practice-app/server/src/models/event.js, practice-app/server/src/models/index.js
1. Check whether the incoming data is valid or not
2. Check whether a lesson with the given lesson_id exists or not.
3. Return events array for the lesson with the given lesson_id
4. Return an error message if an error occurs in any of the previous steps
5. Test the endpoint with Postman
6. Save requests as a collection in Postman
7. Document the endpoint
Now, the get lesson events endpoint is ready for requests.
This PR closes #186, other details can also be seen from that issue.
=> Practice app/feature/get lesson events endpoint 186

practice-app/server/test/get_categories.test.js
As discussed in #173, unit tests for GET /api/categories are implemented.
Implemented tests check for following cases:
- status =  200 : endpoint returns all the existing categories.
=> Implementing tests for GET /api/categories

practice-app/server/test/get_lessons_by_category.test.js, practice-app/server/test/signup.test.js
Apparently if there is a beforeEach function executed outside of describe body and an exception occurs in that beforeEach, the exception can block all the tests.
Right now If I run tests in master branch I get the output of:
```
> bounswe2022group2-practice-app@1.0.0 test
> mocha
database url:  mongodb://localhost:27017/practiceApp
Server is running on 3000
Mongodb Connection
(node:3783) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
GET /lesson/byCategory
1) "before each" hook: addDummyData for "should return validation error if the query parameter is not valid"
0 passing (44ms)
1 failing
1) "before each" hook: addDummyData for "should return validation error if …
```
=> BUGFIX: Inserting beforeEach functions to describe body

practice-app/server/src/api/controllers/rating/createRating.js
As POST /rating is implemented in https://github.com/bounswe/bounswe2022group2/issues/181, there were a "null" text in console between unit test results.
Made the necessary changes and now it does not appear.
=> HOTFIX: POST /rating, null error between unit tests appearing on console fixed

practice-app/server/test/get.ratings.test.js
As discussed in https://github.com/bounswe/bounswe2022group2/issues/173, unit tests for GET /api/categories are implemented.
Implemented tests check for the following cases:
status 200 OK : endpoint returns the relevant ratings.
status 400 Bad Request: one of the request body arguments is missing.
=> Implementing tests for GET /rating

practice-app/server/package-lock.json, practice-app/server/package.json, practice-app/server/src/config/index.js, practice-app/server/src/loaders/mongoose.js
Currently we are establishing a connection with a mongoDB server during tests. This is not desirable in unit tests.
Changes suggested with this implementation make it so that a connection is not established with a DB server.
=> mocking MongoDB connection during tests

practice-app/server/src/api/controllers/rating/createRating.js, practice-app/server/src/api/controllers/rating/createRatingEndpoint.js, practice-app/server/src/api/controllers/rating/getRatingEndpoint.js, practice-app/server/src/models/rating.js, practice-app/server/test/get.ratings.test.js, practice-app/server/test/post.rating.test.js
As I mentioned in #241 , implementation for mentioned endpoints have been changed to provide a more clear user interface. As a result of new status and scenarios in endpoints, the testing of them also must be changed. In this version,
GET/rating
status 200: filtered ratings are returned with query parameters.
status 400: no filtering value entered, bad request.
POST/rating
status 200: rating was successfully created
status 404: lesson does not exist.
=> HOTFIX: Fixing the implementation of GET/rating and POST/rating endpoints

practice-app/server/src/api/controllers/lesson/get_lesson_by_lecturer.js, practice-app/server/src/api/controllers/lesson/index.js, practice-app/server/src/api/routes/lesson.js, practice-app/server/src/models/lesson.js
This pull request contains the implementation regarding lesson creation: a GET endpoint /lesson/byLecturer. Issue regarding this is https://github.com/bounswe/bounswe2022group2/issues/239. Implementation will be tested using Postman.
After the implementation and testing stages are done, I will be preparing a documentation for the API regarding this GET endpoint.
NOTE: As this endpoint required the lesson model to have a lecturer, the model has also been modified. Create lesson endpoint was updated accordingly(see #238 )
=> implement GET lesson by lecturer endpoint

practice-app/frontend/src/components/Signup.vue
We need to derive urls from environment variables so that we can change them easily in AWS server while deploying.
Note: this mistake probably will be made by lots of people, so please do not close the branch.
=> Changing static localhost to URI

practice-app/server/test/drop_lesson.test.js, practice-app/server/test/get_lesson_events.test.js
Due to change in Lesson model, my tests were failing because Lesson documents did not include lecturer field. In this PR, I corrected it.
=> Bugfix drop lesson and get lesson events test update due to lesson model change

practice-app/server/src/api/controllers/user/getEnrolledLessons.js, practice-app/server/src/api/controllers/user/index.js, practice-app/server/src/api/routes/user.js
1. Check whether the incoming data is valid or not
2. Check whether a user with the given user_id exists or not.
3. Return enrolled lessons array of the user with the given user_id
4. Return an error message if an error occurs in any of the previous steps
5. Test the endpoint with Postman
6. Save requests as a collection in Postman
7. Document the endpoint
Now, the get enrolled lessons endpoint is ready for requests.
This PR closes #275, other details can also be seen from that issue.
=> Practice app/feature/get enrolled lessons endpoint 275

practice-app/frontend/src/App.vue, practice-app/frontend/src/components/Event.vue, practice-app/frontend/src/components/Signup.vue, practice-app/frontend/src/route.js
As mentioned in the issue #220, I took the responsibility of implementation of the creating events page of our practice app. Before starting to develop the create event page, I created the corresponding POST endpoint and its unit tests. After being sure that the endpoint works successfully and after testing it with both unit tests and via postman manually, I started to develop the create event page with the Vue.js framework according to the team's decision.
This pull request includes the following actions:
1. Creating a form formation to get required fields for creating an event. Those fields include:
* Event title
* Description
* Date
* Location
* Lesson ID
2. Storing the user_id after signup and passing it to the api request.
3. Connecting the POST event/createEvent endpoint to the …
=> Practice App: Implement Create Event Page

practice-app/server/test/get_enrolled_lessons.test.js
1. Determine the steps to test
2. Create the base test files
3. Write unit tests for the determined steps:
* Created dummy object IDs
* Created 1 dummy category
* Created 2 dummy lessons under that category
* Created 2 dummy users 
* Added dummy category, lessons, users
* Tested the actions determined above
* Deleted dummy created data
Now, the tests for the get enrolled lessons endpoint are ready and tested. The get enrolled lessons endpoint passed all tests successfully without any problem.
This PR closes #277, other details can also be seen from that issue.
=> Added get enrolled lessons tests

practice-app/frontend/src/components/CategoryLessons.vue
After I created the lessons by category screen, there occurred a model update from the other teammates. To be on the same way and successfully show all the fields, I updated the lesson item by adding the lecturer id column and configured it to be compatible with our updated lesson model.
=> BUGFIX: Update lesson item by adding lecturer id column

practice-app/frontend/src/App.vue, practice-app/frontend/src/components/AttendedEvents.vue, practice-app/frontend/src/route.js
As mentioned in the issue #221 , I took the responsibility of implementation of the viewing attended events page of our practice app. Before starting to develop the attended events page, I created the corresponding GET endpoint and its unit tests. After being sure that the endpoint works successfully and after testing it with both unit tests and via postman manually, I started to develop the attended events page with the Vue.js framework according to the team's decision.
This pull request includes the following actions:
1. Creating a list formation to displayed fetched events.
2. Accessing the user_id of the user in the session to get their attended events.
3. Connecting the GET user/attendedEvents endpoint to the Attended Events button on the main navigation.
4. Checking possible …
=> Practice App: Implement Attended Events Page

practice-app/frontend/src/App.vue, practice-app/frontend/src/components/GetEventDetails.vue, practice-app/frontend/src/route.js, practice-app/server/src/api/controllers/event/getEventDetails.js, practice-app/server/test/get_event_details.test.js
As mentioned in the issue #299 , I took the responsibility of implementation of the get specific event details page of our practice app. Before starting to develop the get specific event details page, I created the corresponding endpoints and their unit tests. After being sure that the endpoints work successfully and after testing it with both unit tests and via postman manually, I started to develop the get specific event details page with the Vue.js framework according to the team's decision.
I also updated some parts of the getEventDetails.js and get_event_details.test.js so as to eliminate the error I had previously gotten. All the tests for the parts I am responsible run perfectly now.
* Sending POST requests to our backend server via correct parameters
* …
=> Practice App: Create Get Event Details Screen, Update getEventDetails and Test Part

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/generic_template.yml, .github/ISSUE_TEMPLATE/group_issue_template.yml, .github/ISSUE_TEMPLATE/research_template.yml, README.md
We have new team members and an old member who left the team. Therefore, we need to update our issue diagrams accordingly to match the reviewer and other options with the current team members. I also have some enhancements in the issue templates. You can see all details and all performed actions below:
Closes #338
=> Update issue templates

learnify/docker-compose.yml, learnify/web/.dockerignore, learnify/web/dockerfile
As mentioned in the issue #412 I have implemented the dockerization related code for the frontend of the project, namely dockerfile and .dockerignore files in our web directory and the necessary updates on the docker-compose.yaml file.
You can go to the web directory and run below command to build, (re)create, start, and attach to containers:
`docker compose up`
It uses the latest build's configurations, and since our project is currently under development, running below command will be a better usage (it builds the latest code):
`docker compose up --build`
=> Dockerization of Frontend

learnify/mobile/lib/features/auth/forget-password/model/send_verification_request_model.dart, learnify/mobile/lib/features/auth/forget-password/view-model/forget_password_view_model.dart, learnify/mobile/lib/features/auth/forget-password/view/components/email_form.dart, learnify/mobile/lib/features/auth/service/auth_service.dart, learnify/mobile/lib/features/auth/service/l_auth_service.dart
As #384 explains, this pr responds to connecting  "Send Verification Code" button of the _Forget Password_ screen on the mobile app with the corresponding backend endpoint. 
-When a valid email is entered, app navigates to enter verification screen and a mail is sent via backend.
-When an invalid email is entered, a message for "enter a valid email" is displayed under the email field.
- When an input with valid email syntax (that does not exist) is entered, error message is displayed in a pop up.
Closes #384
=> Mobile: forget password backend 384

learnify/web/src/pages/SignUpForm.js, learnify/web/src/pages/style.css
Our sign up page had appropriate form fields and validation check. However, the connection between the frontend of sign up page and our REST API has not been established yet.
This PR provides a trustfully functioning REST API connection between the sign up page and the appropriate endpoint.
***
* The endpoint used in the sign up form is auth/signup endpoint.
* Upon an unsuccessful response, the string in the response body's resultMessage field is displayed as an error message below the sign up button, with coherence to the validation error messages in the form fields.
***
=> Frontend: Backend connection for sign up page

learnify/backend/api/controllers/auth/login.js
On this PR, when not verified users try to log in, User and corresponding error message returns with 401 status unauthorized.
=> Bugfix: Return error message for not verified users on log in

learnify/mobile/test/forget_password_test.dart
Implements tests for the forget password screen, including:
- widget tests for the screen components
- mock network test for backend connection
closes #383
=> Mobile: implement tests for forget password

learnify/mobile/lib/features/learning-space/view-model/create_learning_space_view_model.dart, learnify/mobile/lib/features/learning-space/view/components/create/learning_space_form.dart, learnify/mobile/lib/features/learning-space/view/create_learning_space_screen.dart, learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart, learnify/mobile/lib/features/view-learning-spaces/view/view_all_screen.dart
This will mainly fix the bugs on the create learning space screen. The categories are not cleared on page changes.
------
1. Clear the selected category list on page transitions
2. Design improvements in the create learning space screen
3. Create a generic customized chip widget to use across the app
=> Mobile: Fix Selected Categories Issue Between Page Transitions

learnify/mobile/lib/core/constants/main_type_definitions.dart, learnify/mobile/lib/core/widgets/dialog/dialog_builder.dart, learnify/mobile/lib/core/widgets/image/annotatable_image.dart, learnify/mobile/lib/core/widgets/image/image_painter.dart, learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart, learnify/mobile/lib/features/learning-space/view/components/chapter/chapter_item.dart, learnify/mobile/lib/features/learning-space/view/components/chapter_image.dart
We have already implemented image annotations with PR #581. However, we should also implement a way/detect these annotations on images. We should capture the gesture of the user with a detector, find the position and show all annotations that contain the touch point. This PR will do the all required things for displaying image annotations.
------
1. Modify the annotation type definitions to return Annotation model
2. Integrate this change and also return Annotation model from the annotate dialog
3. Add annotation info paint info class
4. Added conditional gesture detector into the annotatable image widget
5. Implemented ontapdown function and found the annotation rectangles which contain the selected point
6. Opened the annotation dialog with the contents of the found annotations
------ …
=> Integrate display logic for image annotations

learnify/backend/api/controllers/learning_space/semantic_search_learning_space.js
This PR edits GET /learningspace so that if a query is not given, the endpoint returns the most participated learning spaces.
This feature will be used so that most participated LS can be shown in the main page.
In future, we need to customize these learning space suggestions.
=> 615 getters for learningspaces: get most participated learning spaces if a query is not given

learnify/web/src/pages/LearningSpace.js, learnify/web/src/pages/style.css
In the learning space page illustration and the middle component was overflowing on the footer component. I have fixed the issue by editing css class and adding a space div inbetween.
***
* We use the structure of `<NavBar/><Body/><Footer/>` in our pages. In the css class of the Body we need to add `min-height: calc(100vh - 190px);` so that no overflow can be seen in the Body.
***
***
Closes #636
=> Frontend: HOTFIX Learning Space Page Structural Overflow

learnify/mobile/android/app/src/main/AndroidManifest.xml, learnify/mobile/lib/core/managers/network/network_manager.dart, learnify/mobile/lib/features/learning-space/models/event.dart, learnify/mobile/lib/features/learning-space/models/geolocation/geolocation_model.dart, learnify/mobile/lib/features/learning-space/view/components/events/event_item.dart, learnify/mobile/lib/features/learning-space/view/components/events/event_map.dart, learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart, learnify/mobile/pubspec.yaml
This PR integrates the [Open Street Map](https://www.openstreetmap.org/#map=6/39.031/35.252) into our application. Events have location information inside them which is set by the event creator. Therefore, we need to display the location of the event to the users. We used the free Open Street Map and integrated its map into our event item. This PR also will create and integrate corresponding classes/models.
------
1. Integrate the [Flutter_Map](https://pub.dev/packages/flutter_map) package to embed the Open Street Map.
2. Integrate the [latlong2](https://pub.dev/packages/latlong2) package for common latitude/longitude calculations
3. Create GeoLocation model acc. to the [W3C standards](https://www.w3.org/TR/geolocation/) 
4. Add an event location marker to the map 
5. Modify the event …
=> Mobile: Map integration into the Event Item

learnify/mobile/assets/lang/en.json, learnify/mobile/lib/features/home/view-model/home_view_model.dart, learnify/mobile/lib/features/home/view/home_screen.dart, learnify/mobile/lib/features/learning-space/view-model/learning_space_view_model.dart, learnify/mobile/lib/features/learning-space/view/components/events/event_item.dart, learnify/mobile/lib/features/learning-space/view/components/events/events_list.dart, learnify/mobile/lib/features/learning-space/view/learning_space_detail_screen.dart, learnify/mobile/lib/product/language/language_keys.dart, learnify/mobile/test/events/events_list_preview_test.dart, learnify/mobile/test/events/events_view_test.dart
This PR implements the tests for the events list and event preview item under the learning space detail screen. It will both test the list count, screen details, and also the data of the previewed event item.
------
1. Converts edit event button to attend event button
2. Adds dummy random user data for testing purposes
3. Tests the correctness of the number of events
4. Finds and test the existence of the first event in the list
5. Finds and test the existence of the expansion tile widget under the event item
6. Tests the correctness of the event title and event data information
7. Tests the existence of the create event button
------
Closes #753
=> Mobile: Event List and Preview Test

learnify/web/src/components/LearningSpacePrev.js, learnify/web/src/components/component_styles.css
I have modified the learning space preview box component as it is fully customizable for backend connection. Until now, it featured static components. It featured props parameters. But, those parameters were not passed dynamically, instead as fixed static keywords. This new version accepts the parameters as it will be given by endpoint response.
***
* The props parameters that will be used are:
> * url
> * icon_id
> * title
* The component is now clickable and directs the user to the related learning space page.
* It is now compatible with the response of GET learningspace endpoints.
***
***
Closes #766
=> Frontend: Learning Space Preview Box BE Connection

learnify/annotations-service/backend/api/controllers/post_create_annotation.js, learnify/annotations-service/backend/api/routes/annotations.js
Image annotations do not have source field, only the image URL, so we need to store which post and learning space belong in Annotation ID. This fix provides that.
------
1. Change on post_create_annotation on annotation service
=> Backend FIX: Annotation ID will hold LS and Post ID

learnify/web/src/App.js, learnify/web/src/pages/HomePage.js, learnify/web/src/pages/PopularLearningSpacesPage.js, learnify/web/src/pages/style.css
I have implemented the popular learning spaces page. It is an independent page and can be reached from the related view all button on the home page and displays the most popular 10 learning spaces. The page uses the useEffect hook to retrieve a list of learning spaces from the backend server and displays them using the LearningSpaceDetailBox component. The page also includes a navigation bar and a footer.
***
* The endpoint that is used was /learningspace.
* The page uses the axios library to make a GET request to the backend server to retrieve the list of learning spaces. The request includes an Authorization header with the value of the token stored in local storage.
* The page makes use of the useState hook to store the list of learning spaces in a state variable.
* The list of …
=> Frontend: Popular Learning Spaces Page

learnify/mobile/lib/core/managers/network/network_manager.dart, learnify/mobile/lib/core/widgets/text/annotatable/annotatable_text.dart, learnify/mobile/lib/features/learning-space/models/post_model.dart, learnify/mobile/lib/features/learning-space/view/components/post/post_item.dart
This PR is a hotfix for an empty image list. The carousel slider and indicator will not be shown when there is no image in a post.
------
1. Fix empty image slider visibility
2. Fix the missing character in the post content
=> Mobile: HOTFIX Remove Default Images

learnify/mobile/lib/features/home-wrapper/view-model/home_wrapper_view_model.dart, learnify/mobile/lib/features/home-wrapper/view/home_wrapper_screen.dart, learnify/mobile/lib/features/profile/view-model/profile_view_model.dart, learnify/mobile/lib/features/profile/view/profile_screen.dart, learnify/mobile/test/profile_screen_test.dart
This is a so small change for a failing test on mobile. Due to a hotfix, we need to do before the demo, the profile screen test became invalid and was failing. This PR fixes the problem. It does not change the functionality of the app, it just fixes the failing test due to a last-minute change made this morning.
=> Fix failing profile screen test due to a hotfix before the demo
